"""Subclass of MyFrame2, which is generated by wxFormBuilder."""

import wx
import inegi_app
import make_maps

# Implementing MyFrame2
class MyProject2MyFrame2( inegi_app.MyFrame2 ):
    def __init__( self, parent ):
        inegi_app.MyFrame2.__init__( self, parent )
        self.agees = make_maps.get_all_agee()
        self.m_comboBox7.SetItems([ele.nom_agee for ele in self.agees])
    
    def on_agee_select(self, event):
        """Consulta los agem para un agee y los muestra en lista"""
        index =self.m_comboBox7.GetSelection()
        agee = self.agees[index]
        self.agems = make_maps.get_all_agems_for_agee(agee.cve_agee)
        self.m_comboBox71.SetItems([ele.nom_agem for ele in self.agems])
        event.Skip()
    
    def on_agem_select(self, event):
        """Consulta las localidades para un agee y agem y los muestra en lista"""
        index =self.m_comboBox7.GetSelection()
        agee = self.agees[index]
        index =self.m_comboBox71.GetSelection()
        agem = self.agems[index]
        self.localidades = make_maps.get_all_localidades_for_agem(agee.cve_agee, agem.cve_agem)
        self.m_comboBox711.SetItems([ele.nom_loc for ele in self.localidades])
        event.Skip()
    
    def on_agem_select(self, event):
        """Consulta las localidades para un agee y agem y los muestra en lista"""
        index =self.m_comboBox7.GetSelection()
        agee = self.agees[index]
        index =self.m_comboBox71.GetSelection()
        agem = self.agems[index]
        self.localidades = make_maps.get_all_localidades_for_agem(agee.cve_agee, agem.cve_agem)
        self.m_comboBox711.SetItems([ele.nom_loc for ele in self.localidades])
        event.Skip()
    
    def create_kml(self, event):
        index =self.m_comboBox7.GetSelection()
        agee = self.agees[index]
        index =self.m_comboBox71.GetSelection()
        agem = self.agems[index]
        index =self.m_comboBox711.GetSelection()
        localidad = self.localidades[index]

        make_maps.create_kml(agee.cve_agee, agem.cve_agem, localidad.cve_loc)

    
def main():
    app = wx.App()
    ex = MyProject2MyFrame2(None)
    ex.Show()
    app.MainLoop()

if __name__ == '__main__':
    main()
    